---
- name: Deploy to Digital Ocean
  hosts: do
  remote_user: jan
  vars:
    remote_install_path: /home/{{ ansible_ssh_user }}/github-tools
    remote_home_path: /home/{{ ansible_ssh_user }}
  tasks:
  - name: stop docker container
    command: docker-compose stop
    args:
        chdir: "{{ remote_install_path }}"
  - git:
      repo: git@github.com:JanJoris/github-tools.git
      dest: "{{ remote_install_path }}"
      key_file: ~/.ssh/id_rsa
      clone: no
      update: yes
  - name: copy config file
    copy: src=/home/jan/Git/github-tools/.env dest={{ remote_install_path }}/.env
  - name: start docker container
    command: docker-compose up -d
    args:
      chdir: "{{ remote_install_path }}"